'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { 
  ArrowLeft, FileText, Download, Printer, CheckCircle2, RefreshCcw, 
  ChevronRight, Eye, Sparkles, Bot, Zap, Crown, Upload, Globe,
  Scale, Heart, Building2, Shield, Briefcase, Users, Clock, Copy
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

// Document Types
const DOCUMENT_TYPES = [
  { id: 'contract', name: 'Legal Contract', icon: FileText, color: 'from-blue-500 to-cyan-500' },
  { id: 'agreement', name: 'Agreement', icon: Scale, color: 'from-violet-500 to-purple-500' },
  { id: 'notice', name: 'Legal Notice', icon: Shield, color: 'from-orange-500 to-amber-500' },
  { id: 'petition', name: 'Court Petition', icon: Briefcase, color: 'from-emerald-500 to-green-500' },
  { id: 'affidavit', name: 'Affidavit', icon: FileText, color: 'from-pink-500 to-rose-500' },
  { id: 'power', name: 'Power of Attorney', icon: Users, color: 'from-indigo-500 to-blue-500' },
];

interface DocumentGeneratorProps {
  documentType?: string;
}

export default function DocumentGenerator({ documentType = "Legal Agreement" }: DocumentGeneratorProps) {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [selectedType, setSelectedType] = useState<string | null>(null);
  const [formData, setFormData] = useState<any>({});
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedDoc, setGeneratedDoc] = useState<string | null>(null);

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      const docType = DOCUMENT_TYPES.find(d => d.id === selectedType)?.name || documentType;
      setGeneratedDoc(`
═══════════════════════════════════════════════════
                    ${docType.toUpperCase()}
═══════════════════════════════════════════════════

Document Number: EHB-DOC-${Date.now().toString().slice(-6)}
Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}
Platform: EHB Law AI Legal Services

───────────────────────────────────────────────────
                      PARTIES
───────────────────────────────────────────────────

FIRST PARTY (Party A):
Name: ${formData.partyA || '[Full Legal Name]'}
Address: ${formData.addressA || '[Address]'}
CNIC/ID: ${formData.idA || '[ID Number]'}

SECOND PARTY (Party B):
Name: ${formData.partyB || '[Full Legal Name]'}
Address: ${formData.addressB || '[Address]'}
CNIC/ID: ${formData.idB || '[ID Number]'}

───────────────────────────────────────────────────
                 TERMS & CONDITIONS
───────────────────────────────────────────────────

WHEREAS, the parties have agreed to enter into this
${docType} under the following terms:

1. PURPOSE
   This agreement establishes the legal relationship
   between the parties as specified herein.

2. JURISDICTION
   This document is governed by the laws of
   ${formData.location || '[Jurisdiction]'}.

3. EFFECTIVE DATE
   This agreement shall commence on
   ${formData.date || new Date().toLocaleDateString()}.

4. GENERAL PROVISIONS
   [AI-GENERATED LEGAL CLAUSES SPECIFIC TO ${docType.toUpperCase()}]
   
   4.1 Both parties agree to fulfill their 
       respective obligations in good faith.
   
   4.2 Any disputes shall be resolved through
       arbitration under EHB Law platform.
   
   4.3 Modifications require written consent
       from both parties.

───────────────────────────────────────────────────
                    SIGNATURES
───────────────────────────────────────────────────

Party A                        Party B

____________________          ____________________
${formData.partyA || '[Name]'}        ${formData.partyB || '[Name]'}

Date: _______________          Date: _______________


Witness 1: _______________    Witness 2: _______________

═══════════════════════════════════════════════════
         GENERATED BY EHB LAW AI PLATFORM
       www.ehblaw.com | Verified Document
═══════════════════════════════════════════════════
      `);
      setStep(4);
    }, 3000);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-[#020617] via-slate-900 to-[#020617]">
      {/* Header */}
      <section className="relative overflow-hidden border-b border-white/5">
        <div className="absolute inset-0">
          <div className="absolute top-0 left-1/4 w-96 h-96 bg-emerald-500/10 rounded-full blur-[150px]" />
          <div className="absolute top-0 right-1/4 w-96 h-96 bg-[#D4AF37]/10 rounded-full blur-[150px]" />
        </div>

        <div className="relative max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <button 
            onClick={() => router.back()}
            className="flex items-center gap-2 text-ehb-textMuted hover:text-white transition-colors mb-6"
          >
            <ArrowLeft size={18} />
            <span className="text-sm font-medium">Back</span>
          </button>

          <div className="flex items-center justify-between">
            <div>
              <div className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-500/10 border border-emerald-500/30 rounded-full text-emerald-400 text-sm font-medium mb-4">
                <Sparkles size={16} />
                AI Document Generator
              </div>
              <h1 className="text-3xl md:text-4xl font-bold text-white mb-2">
                Create Legal Documents
                <span className="block text-[#D4AF37]">Instantly with AI</span>
              </h1>
              <p className="text-ehb-textMuted">Generate professional legal documents in seconds</p>
            </div>

            {/* Progress */}
            <div className="hidden md:flex items-center gap-2">
              {['Select', 'Parties', 'Details', 'Generate', 'Download'].map((label, i) => (
                <div key={label} className="flex items-center">
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold transition-all ${
                    i <= step 
                      ? 'bg-gradient-to-r from-emerald-500 to-green-500 text-white' 
                      : 'bg-white/10 text-ehb-textMuted'
                  }`}>
                    {i < step ? <CheckCircle2 size={16} /> : i + 1}
                  </div>
                  {i < 4 && <div className={`w-8 h-1 mx-1 rounded ${i < step ? 'bg-emerald-500' : 'bg-white/10'}`} />}
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid lg:grid-cols-2 gap-8">
          {/* Form Section */}
          <div>
            <AnimatePresence mode="wait">
              {/* Step 0: Select Document Type */}
              {step === 0 && (
                <motion.div 
                  key="step0"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -20 }}
                  className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6"
                >
                  <h2 className="text-xl font-bold text-white mb-2">Select Document Type</h2>
                  <p className="text-sm text-ehb-textMuted mb-6">Choose the type of legal document you need</p>
                  
                  <div className="grid grid-cols-2 gap-4">
                    {DOCUMENT_TYPES.map((type) => (
                      <button
                        key={type.id}
                        onClick={() => setSelectedType(type.id)}
                        className={`p-4 rounded-xl border-2 text-left transition-all ${
                          selectedType === type.id
                            ? 'border-emerald-500 bg-emerald-500/10'
                            : 'border-white/10 bg-white/5 hover:border-white/30'
                        }`}
                      >
                        <div className={`w-10 h-10 rounded-lg bg-gradient-to-br ${type.color} flex items-center justify-center mb-3`}>
                          <type.icon className="text-white" size={20} />
                        </div>
                        <h3 className="text-white font-medium">{type.name}</h3>
                      </button>
                    ))}
                  </div>
                  
                  <button 
                    onClick={() => setStep(1)}
                    disabled={!selectedType}
                    className="w-full mt-6 py-4 bg-gradient-to-r from-emerald-500 to-green-500 text-white font-bold rounded-xl hover:shadow-lg hover:shadow-emerald-500/30 transition-all disabled:opacity-50 flex items-center justify-center gap-2"
                  >
                    Continue <ChevronRight size={18} />
                  </button>
                </motion.div>
              )}

              {/* Step 1: Party A Information */}
              {step === 1 && (
                <motion.div 
                  key="step1"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -20 }}
                  className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6"
                >
                  <h2 className="text-xl font-bold text-white mb-2">First Party Details</h2>
                  <p className="text-sm text-ehb-textMuted mb-6">Enter the information for Party A</p>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-xs font-bold text-ehb-textMuted mb-2">FULL LEGAL NAME</label>
                      <input 
                        type="text" 
                        placeholder="Enter full name"
                        className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-white placeholder:text-ehb-textMuted outline-none focus:border-emerald-500 transition-all"
                        value={formData.partyA || ''}
                        onChange={(e) => setFormData({...formData, partyA: e.target.value})}
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-ehb-textMuted mb-2">ADDRESS</label>
                      <input 
                        type="text" 
                        placeholder="Enter address"
                        className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-white placeholder:text-ehb-textMuted outline-none focus:border-emerald-500 transition-all"
                        value={formData.addressA || ''}
                        onChange={(e) => setFormData({...formData, addressA: e.target.value})}
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-ehb-textMuted mb-2">CNIC/ID NUMBER</label>
                      <input 
                        type="text" 
                        placeholder="Enter ID number"
                        className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-white placeholder:text-ehb-textMuted outline-none focus:border-emerald-500 transition-all"
                        value={formData.idA || ''}
                        onChange={(e) => setFormData({...formData, idA: e.target.value})}
                      />
                    </div>
                  </div>
                  
                  <div className="flex gap-4 mt-6">
                    <button 
                      onClick={() => setStep(0)}
                      className="flex-1 py-4 bg-white/10 text-white font-bold rounded-xl hover:bg-white/20 transition-all"
                    >
                      Back
                    </button>
                    <button 
                      onClick={() => setStep(2)}
                      className="flex-[2] py-4 bg-gradient-to-r from-emerald-500 to-green-500 text-white font-bold rounded-xl hover:shadow-lg hover:shadow-emerald-500/30 transition-all flex items-center justify-center gap-2"
                    >
                      Continue <ChevronRight size={18} />
                    </button>
                  </div>
                </motion.div>
              )}

              {/* Step 2: Party B Information */}
              {step === 2 && (
                <motion.div 
                  key="step2"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -20 }}
                  className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6"
                >
                  <h2 className="text-xl font-bold text-white mb-2">Second Party Details</h2>
                  <p className="text-sm text-ehb-textMuted mb-6">Enter the information for Party B</p>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-xs font-bold text-ehb-textMuted mb-2">FULL LEGAL NAME</label>
                      <input 
                        type="text" 
                        placeholder="Enter full name"
                        className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-white placeholder:text-ehb-textMuted outline-none focus:border-emerald-500 transition-all"
                        value={formData.partyB || ''}
                        onChange={(e) => setFormData({...formData, partyB: e.target.value})}
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-ehb-textMuted mb-2">ADDRESS</label>
                      <input 
                        type="text" 
                        placeholder="Enter address"
                        className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-white placeholder:text-ehb-textMuted outline-none focus:border-emerald-500 transition-all"
                        value={formData.addressB || ''}
                        onChange={(e) => setFormData({...formData, addressB: e.target.value})}
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-ehb-textMuted mb-2">CNIC/ID NUMBER</label>
                      <input 
                        type="text" 
                        placeholder="Enter ID number"
                        className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-white placeholder:text-ehb-textMuted outline-none focus:border-emerald-500 transition-all"
                        value={formData.idB || ''}
                        onChange={(e) => setFormData({...formData, idB: e.target.value})}
                      />
                    </div>
                  </div>
                  
                  <div className="flex gap-4 mt-6">
                    <button 
                      onClick={() => setStep(1)}
                      className="flex-1 py-4 bg-white/10 text-white font-bold rounded-xl hover:bg-white/20 transition-all"
                    >
                      Back
                    </button>
                    <button 
                      onClick={() => setStep(3)}
                      className="flex-[2] py-4 bg-gradient-to-r from-emerald-500 to-green-500 text-white font-bold rounded-xl hover:shadow-lg hover:shadow-emerald-500/30 transition-all flex items-center justify-center gap-2"
                    >
                      Continue <ChevronRight size={18} />
                    </button>
                  </div>
                </motion.div>
              )}

              {/* Step 3: Document Details */}
              {step === 3 && (
                <motion.div 
                  key="step3"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -20 }}
                  className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6"
                >
                  <h2 className="text-xl font-bold text-white mb-2">Document Details</h2>
                  <p className="text-sm text-ehb-textMuted mb-6">Enter additional document information</p>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-xs font-bold text-ehb-textMuted mb-2">JURISDICTION/LOCATION</label>
                      <input 
                        type="text" 
                        placeholder="e.g. Dubai, UAE"
                        className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-white placeholder:text-ehb-textMuted outline-none focus:border-emerald-500 transition-all"
                        value={formData.location || ''}
                        onChange={(e) => setFormData({...formData, location: e.target.value})}
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-ehb-textMuted mb-2">EFFECTIVE DATE</label>
                      <input 
                        type="date" 
                        className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-white outline-none focus:border-emerald-500 transition-all"
                        value={formData.date || ''}
                        onChange={(e) => setFormData({...formData, date: e.target.value})}
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-ehb-textMuted mb-2">ADDITIONAL NOTES (OPTIONAL)</label>
                      <textarea 
                        placeholder="Any specific terms or conditions..."
                        rows={3}
                        className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-white placeholder:text-ehb-textMuted outline-none focus:border-emerald-500 transition-all resize-none"
                        value={formData.notes || ''}
                        onChange={(e) => setFormData({...formData, notes: e.target.value})}
                      />
                    </div>
                  </div>
                  
                  <div className="flex gap-4 mt-6">
                    <button 
                      onClick={() => setStep(2)}
                      className="flex-1 py-4 bg-white/10 text-white font-bold rounded-xl hover:bg-white/20 transition-all"
                    >
                      Back
                    </button>
                    <button 
                      onClick={handleGenerate}
                      disabled={isGenerating}
                      className="flex-[2] py-4 bg-gradient-to-r from-emerald-500 to-green-500 text-white font-bold rounded-xl hover:shadow-lg hover:shadow-emerald-500/30 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
                    >
                      {isGenerating ? (
                        <>
                          <RefreshCcw className="animate-spin" size={18} />
                          AI Generating...
                        </>
                      ) : (
                        <>
                          <Zap size={18} />
                          Generate Document
                        </>
                      )}
                    </button>
                  </div>
                </motion.div>
              )}

              {/* Step 4: Success */}
              {step === 4 && (
                <motion.div 
                  key="step4"
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6"
                >
                  <div className="text-center p-6 bg-emerald-500/10 border border-emerald-500/30 rounded-xl mb-6">
                    <CheckCircle2 className="mx-auto text-emerald-400 mb-4" size={48} />
                    <h2 className="text-2xl font-bold text-white mb-2">Document Generated!</h2>
                    <p className="text-ehb-textMuted">Your {DOCUMENT_TYPES.find(d => d.id === selectedType)?.name} is ready</p>
                  </div>
                  
                  <div className="grid grid-cols-2 gap-4 mb-4">
                    <button className="py-3 bg-gradient-to-r from-[#D4AF37] to-[#B8860B] text-slate-900 font-bold rounded-xl hover:shadow-lg hover:shadow-[#D4AF37]/30 transition-all flex items-center justify-center gap-2">
                      <Download size={18} />
                      Download PDF
                    </button>
                    <button className="py-3 bg-white/10 text-white font-bold rounded-xl hover:bg-white/20 transition-all flex items-center justify-center gap-2">
                      <Printer size={18} />
                      Print
                    </button>
                  </div>
                  
                  <div className="flex gap-4">
                    <button className="flex-1 py-3 bg-white/10 text-white font-medium rounded-xl hover:bg-white/20 transition-all flex items-center justify-center gap-2">
                      <Copy size={16} />
                      Copy Text
                    </button>
                    <button 
                      onClick={() => {
                        setStep(0);
                        setSelectedType(null);
                        setFormData({});
                        setGeneratedDoc(null);
                      }}
                      className="flex-1 py-3 bg-white/10 text-white font-medium rounded-xl hover:bg-white/20 transition-all"
                    >
                      Create New
                    </button>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Preview Section */}
          <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6 min-h-[500px] flex flex-col">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Eye className="text-[#D4AF37]" size={18} />
                <span className="text-sm font-bold text-white">Live Preview</span>
              </div>
              <div className="flex gap-1.5">
                <div className="w-3 h-3 rounded-full bg-red-500/50" />
                <div className="w-3 h-3 rounded-full bg-yellow-500/50" />
                <div className="w-3 h-3 rounded-full bg-emerald-500/50" />
              </div>
            </div>

            <div className="flex-1 bg-slate-950 rounded-xl p-6 overflow-y-auto font-mono text-sm leading-relaxed whitespace-pre-wrap text-ehb-textBody border border-slate-800">
              {isGenerating ? (
                <div className="h-full flex flex-col items-center justify-center text-center">
                  <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-emerald-500 to-green-500 flex items-center justify-center mb-4">
                    <Bot className="text-white animate-pulse" size={32} />
                  </div>
                  <p className="text-emerald-400 font-bold mb-2">AI is drafting your document...</p>
                  <p className="text-ehb-textMuted text-xs">Analyzing legal requirements and formatting</p>
                </div>
              ) : generatedDoc ? (
                generatedDoc
              ) : (
                <div className="h-full flex flex-col items-center justify-center text-center text-ehb-textMuted">
                  <FileText size={48} className="mb-4 opacity-30" />
                  <p className="font-sans max-w-[250px]">Complete the form to see your document preview here</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
