apiVersion: v1
kind: ConfigMap
metadata:
  name: ehb-config
data:
  NODE_ENV: "production"
  REDIS_URL: "redis://redis:6379"
  DMO_REALTIME_PORT: "5000"
  DMO_REALTIME_CORS_ORIGIN: "*"
  EHB_MONITORING_ENABLED: "true"
  EHB_MONITORING_SAMPLE_RATE: "0.1"
  EHB_MIDDLEWARE_DEV_BYPASS: "false"
