// =============================================================================
// EHB DATABASE - MOCK DATA
// Sample data for development and testing
// =============================================================================

import {
  User, Lawyer, Case, CaseDocument, LegalService, Payment,
  Subscription, AIAgent, CaseTimelineEvent, Notification,
  WorkingHours
} from './schema';

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

const generateId = () => `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
const randomDate = (start: Date, end: Date) => 
  new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));

const DEFAULT_WORKING_HOURS: WorkingHours = {
  monday: { start: '09:00', end: '18:00', closed: false },
  tuesday: { start: '09:00', end: '18:00', closed: false },
  wednesday: { start: '09:00', end: '18:00', closed: false },
  thursday: { start: '09:00', end: '18:00', closed: false },
  friday: { start: '09:00', end: '17:00', closed: false },
  saturday: { start: '10:00', end: '14:00', closed: false },
  sunday: { start: '00:00', end: '00:00', closed: true },
};

// =============================================================================
// MOCK USERS
// =============================================================================

export const MOCK_USERS: User[] = [
  {
    user_id: 'user-001',
    email: 'ahmad.khan@email.com',
    password_hash: '$2b$10$xxxxx',
    phone: '+92300-1234567',
    phone_verified: true,
    email_verified: true,
    first_name: 'Ahmad',
    last_name: 'Khan',
    full_name: 'Ahmad Khan',
    display_name: 'Ahmad K.',
    avatar_url: '/avatars/ahmad.jpg',
    gender: 'male',
    date_of_birth: new Date('1985-03-15'),
    country: 'PK',
    country_name: 'Pakistan',
    state_province: 'Punjab',
    city: 'Lahore',
    address: '123 Gulberg III',
    postal_code: '54000',
    timezone: 'Asia/Karachi',
    language: 'ur',
    secondary_language: 'en',
    preferred_currency: 'PKR',
    role: 'client',
    status: 'active',
    account_type: 'premium',
    two_factor_enabled: true,
    last_login: new Date('2026-03-12T10:30:00'),
    last_ip: '192.168.1.100',
    login_count: 45,
    failed_login_attempts: 0,
    referral_code: 'AHMAD2026',
    created_at: new Date('2025-06-15'),
    updated_at: new Date('2026-03-12'),
  },
  {
    user_id: 'user-002',
    email: 'fatima.ali@email.com',
    password_hash: '$2b$10$xxxxx',
    phone: '+92321-9876543',
    phone_verified: true,
    email_verified: true,
    first_name: 'Fatima',
    last_name: 'Ali',
    full_name: 'Fatima Ali',
    gender: 'female',
    date_of_birth: new Date('1990-08-22'),
    country: 'PK',
    country_name: 'Pakistan',
    state_province: 'Sindh',
    city: 'Karachi',
    timezone: 'Asia/Karachi',
    language: 'en',
    preferred_currency: 'PKR',
    role: 'client',
    status: 'active',
    account_type: 'free',
    two_factor_enabled: false,
    login_count: 12,
    failed_login_attempts: 0,
    referral_code: 'FATIMA2026',
    created_at: new Date('2026-01-10'),
    updated_at: new Date('2026-03-10'),
  },
  {
    user_id: 'user-003',
    email: 'john.williams@email.com',
    password_hash: '$2b$10$xxxxx',
    phone: '+971501234567',
    phone_verified: true,
    email_verified: true,
    first_name: 'John',
    last_name: 'Williams',
    full_name: 'John Williams',
    gender: 'male',
    country: 'AE',
    country_name: 'United Arab Emirates',
    city: 'Dubai',
    timezone: 'Asia/Dubai',
    language: 'en',
    preferred_currency: 'AED',
    role: 'client',
    status: 'active',
    account_type: 'enterprise',
    two_factor_enabled: true,
    login_count: 78,
    failed_login_attempts: 0,
    referral_code: 'JOHN2026',
    created_at: new Date('2025-03-20'),
    updated_at: new Date('2026-03-11'),
  },
];

// =============================================================================
// MOCK LAWYERS
// =============================================================================

export const MOCK_LAWYERS: Lawyer[] = [
  {
    lawyer_id: 'lawyer-001',
    user_id: 'user-lawyer-001',
    bar_council_id: 'PBC-2010-12345',
    bar_council_name: 'Pakistan Bar Council',
    license_number: 'ADV-LHC-2010-001',
    license_issue_date: new Date('2010-06-15'),
    license_status: 'verified',
    professional_title: 'Advocate High Court',
    bio: 'Experienced property law specialist with 15+ years of practice in Lahore High Court.',
    bio_urdu: 'لاہور ہائی کورٹ میں 15+ سال کے تجربے کے ساتھ پراپرٹی لاء کے ماہر۔',
    profile_photo_url: '/lawyers/imran-sheikh.jpg',
    experience_years: 15,
    cases_handled: 450,
    cases_won: 380,
    success_rate: 84.4,
    primary_specialization: 'property_dispute',
    secondary_specializations: ['civil_litigation', 'contract_dispute', 'land_ownership'],
    practice_areas: ['Property Law', 'Civil Law', 'Contract Law', 'Real Estate'],
    overall_rating: 4.9,
    total_reviews: 234,
    sql_level: 5,
    is_available: true,
    availability_status: 'online',
    working_hours: DEFAULT_WORKING_HOURS,
    accepts_new_cases: true,
    max_active_cases: 25,
    current_active_cases: 18,
    office_address: '45 Court Road, Lahore',
    office_city: 'Lahore',
    office_country: 'PK',
    practice_jurisdictions: ['Pakistan'],
    courts_practiced: ['Lahore High Court', 'Civil Courts', 'District Courts'],
    languages_spoken: ['English', 'Urdu', 'Punjabi'],
    consultation_fee: 5000,
    consultation_currency: 'PKR',
    hourly_rate: 10000,
    case_based_min_fee: 50000,
    case_based_max_fee: 500000,
    monthly_retainer_fee: 100000,
    annual_contract_fee: 1000000,
    accepts_payment_plans: true,
    verification_status: 'verified',
    verified_at: new Date('2025-01-15'),
    verification_documents: ['/docs/bar-card.pdf', '/docs/cnic.pdf'],
    background_check_completed: true,
    status: 'active',
    featured: true,
    badges: ['Top Rated', 'Quick Responder', 'Expert', '10+ Years'],
    response_time_hours: 1,
    joined_platform_at: new Date('2024-06-01'),
    last_active_at: new Date('2026-03-12T11:00:00'),
    created_at: new Date('2024-06-01'),
    updated_at: new Date('2026-03-12'),
  },
  {
    lawyer_id: 'lawyer-002',
    user_id: 'user-lawyer-002',
    bar_council_id: 'PBC-2012-67890',
    bar_council_name: 'Pakistan Bar Council',
    license_number: 'ADV-SHC-2012-002',
    license_issue_date: new Date('2012-09-20'),
    license_status: 'verified',
    professional_title: 'Advocate Supreme Court',
    bio: 'Family law expert specializing in divorce, custody, and marriage disputes.',
    bio_urdu: 'طلاق، حضانت اور شادی کے تنازعات میں ماہر۔',
    profile_photo_url: '/lawyers/sara-malik.jpg',
    experience_years: 12,
    cases_handled: 320,
    cases_won: 275,
    success_rate: 85.9,
    primary_specialization: 'divorce',
    secondary_specializations: ['child_custody', 'family_dispute', 'marriage_registration'],
    practice_areas: ['Family Law', 'Divorce', 'Child Custody', 'Women Rights'],
    overall_rating: 4.8,
    total_reviews: 189,
    sql_level: 4,
    is_available: true,
    availability_status: 'online',
    working_hours: DEFAULT_WORKING_HOURS,
    accepts_new_cases: true,
    max_active_cases: 20,
    current_active_cases: 14,
    office_address: '78 Clifton Road, Karachi',
    office_city: 'Karachi',
    office_country: 'PK',
    practice_jurisdictions: ['Pakistan'],
    courts_practiced: ['Supreme Court', 'Sindh High Court', 'Family Courts'],
    languages_spoken: ['English', 'Urdu', 'Sindhi'],
    consultation_fee: 4500,
    consultation_currency: 'PKR',
    hourly_rate: 8000,
    case_based_min_fee: 45000,
    case_based_max_fee: 400000,
    monthly_retainer_fee: 90000,
    accepts_payment_plans: true,
    verification_status: 'verified',
    verified_at: new Date('2025-02-20'),
    verification_documents: ['/docs/bar-card-sara.pdf'],
    background_check_completed: true,
    status: 'active',
    featured: true,
    badges: ['Family Law Expert', 'Trusted', 'Women Advocate'],
    response_time_hours: 2,
    joined_platform_at: new Date('2024-08-15'),
    last_active_at: new Date('2026-03-12T09:30:00'),
    created_at: new Date('2024-08-15'),
    updated_at: new Date('2026-03-12'),
  },
  {
    lawyer_id: 'lawyer-003',
    user_id: 'user-lawyer-003',
    bar_council_id: 'DIFC-2008-11111',
    bar_council_name: 'Dubai International Financial Centre Courts',
    license_number: 'ADV-UAE-2008-003',
    license_issue_date: new Date('2008-03-10'),
    license_status: 'verified',
    professional_title: 'International Legal Consultant',
    bio: 'Corporate law expert with international practice in UAE, UK, and Pakistan.',
    bio_urdu: 'UAE، UK اور پاکستان میں بین الاقوامی پریکٹس کے ساتھ کارپوریٹ لاء ماہر۔',
    profile_photo_url: '/lawyers/ahmed-hassan.jpg',
    experience_years: 18,
    cases_handled: 520,
    cases_won: 468,
    success_rate: 90,
    primary_specialization: 'corporate_law',
    secondary_specializations: ['merger_acquisition', 'intellectual_property', 'contract_dispute'],
    practice_areas: ['Corporate Law', 'M&A', 'International Trade', 'Business Law'],
    overall_rating: 4.95,
    total_reviews: 312,
    sql_level: 5,
    is_available: true,
    availability_status: 'online',
    working_hours: DEFAULT_WORKING_HOURS,
    accepts_new_cases: true,
    max_active_cases: 15,
    current_active_cases: 12,
    office_address: 'DIFC Gate Building, Dubai',
    office_city: 'Dubai',
    office_country: 'AE',
    practice_jurisdictions: ['UAE', 'UK', 'Pakistan'],
    courts_practiced: ['DIFC Courts', 'Dubai Courts', 'UK Commercial Court'],
    languages_spoken: ['English', 'Arabic', 'Urdu'],
    consultation_fee: 15000,
    consultation_currency: 'AED',
    hourly_rate: 25000,
    case_based_min_fee: 120000,
    case_based_max_fee: 2000000,
    monthly_retainer_fee: 250000,
    annual_contract_fee: 2500000,
    accepts_payment_plans: true,
    verification_status: 'verified',
    verified_at: new Date('2024-12-01'),
    verification_documents: ['/docs/difc-license.pdf'],
    background_check_completed: true,
    status: 'active',
    featured: true,
    badges: ['Premium', 'Corporate Expert', 'International', 'Top Rated'],
    response_time_hours: 0.5,
    joined_platform_at: new Date('2024-03-01'),
    last_active_at: new Date('2026-03-12T10:00:00'),
    created_at: new Date('2024-03-01'),
    updated_at: new Date('2026-03-12'),
  },
];

// =============================================================================
// MOCK CASES
// =============================================================================

export const MOCK_CASES: Case[] = [
  {
    case_id: 'case-001',
    case_number: 'EHB-2026-001234',
    client_id: 'user-001',
    lawyer_id: 'lawyer-001',
    case_type: 'property_dispute',
    case_category: 'Property Law',
    title: 'Land Ownership Dispute - Gulberg Property',
    title_urdu: 'گلبرگ پراپرٹی - زمین کی ملکیت کا تنازعہ',
    description: 'Dispute over ownership of 2 kanal residential plot in Gulberg III.',
    description_urdu: 'گلبرگ III میں 2 کنال رہائشی پلاٹ کی ملکیت کا تنازعہ۔',
    status: 'in_progress',
    priority: 'high',
    stage: 'court_hearing',
    progress_percentage: 65,
    jurisdiction_country: 'PK',
    jurisdiction_state: 'Punjab',
    jurisdiction_city: 'Lahore',
    court_name: 'Civil Court Lahore',
    court_case_number: 'CC-LHR-2026-5678',
    incident_date: new Date('2025-06-15'),
    filing_date: new Date('2026-02-15'),
    assigned_date: new Date('2026-02-17'),
    first_hearing_date: new Date('2026-03-01'),
    next_hearing_date: new Date('2026-03-25'),
    expected_completion_date: new Date('2026-08-15'),
    estimated_cost: 150000,
    actual_cost: 75000,
    currency: 'PKR',
    payment_status: 'in_escrow',
    escrow_amount: 100000,
    ai_success_prediction: 72,
    ai_recommended_strategy: 'Submit ownership documents and request possession order.',
    ai_estimated_duration_days: 180,
    ai_risk_assessment: 'Medium risk - opposing party has partial documentation',
    tags: ['property', 'urgent', 'high-value'],
    source: 'ai_agent',
    created_at: new Date('2026-02-15'),
    updated_at: new Date('2026-03-12'),
  },
  {
    case_id: 'case-002',
    case_number: 'EHB-2026-001235',
    client_id: 'user-002',
    lawyer_id: 'lawyer-002',
    case_type: 'divorce',
    case_category: 'Family Law',
    title: 'Divorce Settlement - Mutual Consent',
    title_urdu: 'طلاق کا تصفیہ - باہمی رضامندی',
    description: 'Mutual consent divorce with child custody arrangement.',
    description_urdu: 'بچے کی حضانت کے انتظام کے ساتھ باہمی رضامندی سے طلاق۔',
    status: 'assigned',
    priority: 'medium',
    stage: 'mediation',
    progress_percentage: 35,
    jurisdiction_country: 'PK',
    jurisdiction_state: 'Sindh',
    jurisdiction_city: 'Karachi',
    court_name: 'Family Court Karachi',
    filing_date: new Date('2026-03-01'),
    assigned_date: new Date('2026-03-03'),
    estimated_cost: 80000,
    actual_cost: 25000,
    currency: 'PKR',
    payment_status: 'partial',
    escrow_amount: 50000,
    ai_success_prediction: 88,
    tags: ['family', 'divorce', 'custody'],
    source: 'web',
    created_at: new Date('2026-03-01'),
    updated_at: new Date('2026-03-10'),
  },
  {
    case_id: 'case-003',
    case_number: 'EHB-2026-001236',
    client_id: 'user-003',
    lawyer_id: 'lawyer-003',
    case_type: 'corporate_law',
    case_category: 'Corporate Law',
    title: 'Business Contract Breach - Tech Solutions Ltd',
    title_urdu: 'کاروباری معاہدے کی خلاف ورزی',
    description: 'Contract breach by vendor resulting in $500K losses.',
    status: 'submitted',
    priority: 'critical',
    stage: 'review',
    progress_percentage: 15,
    jurisdiction_country: 'AE',
    jurisdiction_city: 'Dubai',
    court_name: 'DIFC Courts',
    filing_date: new Date('2026-03-10'),
    estimated_cost: 500000,
    actual_cost: 50000,
    currency: 'AED',
    payment_status: 'unpaid',
    escrow_amount: 0,
    ai_success_prediction: 78,
    tags: ['corporate', 'international', 'high-value'],
    source: 'referral',
    created_at: new Date('2026-03-10'),
    updated_at: new Date('2026-03-12'),
  },
];

// =============================================================================
// MOCK LEGAL SERVICES
// =============================================================================

export const MOCK_LEGAL_SERVICES: LegalService[] = [
  {
    service_id: 'service-001',
    name: 'Divorce Filing',
    name_urdu: 'طلاق کی درخواست',
    slug: 'divorce-filing',
    description: 'Complete divorce filing service including documentation and court representation.',
    description_urdu: 'دستاویزات اور عدالتی نمائندگی سمیت مکمل طلاق فائلنگ سروس۔',
    category: 'Family Law',
    category_urdu: 'خاندانی قانون',
    related_case_types: ['divorce', 'child_custody', 'family_dispute'],
    base_price: 50000,
    max_price: 200000,
    currency: 'PKR',
    pricing_type: 'range',
    includes_consultation: true,
    features: ['Initial consultation', 'Document preparation', 'Court filing', 'Hearing representation'],
    features_urdu: ['ابتدائی مشاورت', 'دستاویزات کی تیاری', 'عدالت میں فائلنگ', 'سماعت میں نمائندگی'],
    requirements: ['Marriage Certificate', 'CNIC copies', 'Address proof'],
    estimated_duration_days: 90,
    is_active: true,
    available_countries: ['PK', 'AE', 'UK'],
    available_languages: ['en', 'ur'],
    icon: 'heart-crack',
    display_order: 1,
    featured: true,
    total_cases: 1250,
    success_rate: 92,
    average_rating: 4.7,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2026-03-01'),
  },
  {
    service_id: 'service-002',
    name: 'Property Dispute Resolution',
    name_urdu: 'پراپرٹی تنازعہ حل',
    slug: 'property-dispute',
    description: 'Expert legal assistance for property ownership and land disputes.',
    description_urdu: 'پراپرٹی کی ملکیت اور زمین کے تنازعات کے لیے ماہر قانونی مدد۔',
    category: 'Property Law',
    category_urdu: 'پراپرٹی قانون',
    related_case_types: ['property_dispute', 'land_ownership', 'property_transfer'],
    base_price: 75000,
    max_price: 500000,
    currency: 'PKR',
    pricing_type: 'range',
    includes_consultation: true,
    features: ['Property verification', 'Legal notice', 'Court proceedings', 'Settlement negotiation'],
    features_urdu: ['پراپرٹی تصدیق', 'قانونی نوٹس', 'عدالتی کارروائی', 'تصفیہ مذاکرات'],
    requirements: ['Property documents', 'Ownership proof', 'ID documents'],
    estimated_duration_days: 180,
    is_active: true,
    available_countries: ['PK', 'AE', 'UK', 'US'],
    available_languages: ['en', 'ur', 'ar'],
    icon: 'building',
    display_order: 2,
    featured: true,
    total_cases: 980,
    success_rate: 85,
    average_rating: 4.6,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2026-03-01'),
  },
];

// =============================================================================
// MOCK AI AGENTS
// =============================================================================

export const MOCK_AI_AGENTS: AIAgent[] = [
  {
    agent_id: 'agent-001',
    agent_type: 'orchestrator',
    name: 'AI Orchestrator',
    name_urdu: 'AI آرکیسٹریٹر',
    description: 'Central AI brain that coordinates all other agents',
    description_urdu: 'مرکزی AI دماغ جو تمام دوسرے ایجنٹس کو منظم کرتا ہے',
    version: '2.0.0',
    config: { maxConcurrentTasks: 100, timeout: 30000 },
    capabilities: ['task_routing', 'workflow_management', 'agent_coordination', 'priority_handling'],
    dependencies: [],
    status: 'active',
    is_enabled: true,
    tasks_completed: 15678,
    tasks_in_progress: 45,
    tasks_failed: 23,
    average_response_time_ms: 250,
    accuracy_percentage: 98.5,
    uptime_percentage: 99.99,
    memory_usage_mb: 512,
    cpu_usage_percentage: 25,
    max_concurrent_tasks: 100,
    last_active_at: new Date(),
    created_at: new Date('2024-01-01'),
    updated_at: new Date(),
  },
  {
    agent_id: 'agent-002',
    agent_type: 'case_management',
    name: 'Case Management Agent',
    name_urdu: 'کیس مینجمنٹ ایجنٹ',
    description: 'Manages legal case lifecycle from creation to completion',
    description_urdu: 'تخلیق سے تکمیل تک قانونی کیس کا انتظام',
    version: '1.5.0',
    config: { autoAssign: true, notifyOnStatusChange: true },
    capabilities: ['case_creation', 'status_tracking', 'timeline_management', 'assignment'],
    dependencies: ['orchestrator'],
    status: 'active',
    is_enabled: true,
    tasks_completed: 8945,
    tasks_in_progress: 89,
    tasks_failed: 12,
    average_response_time_ms: 180,
    accuracy_percentage: 97.8,
    uptime_percentage: 99.95,
    memory_usage_mb: 256,
    cpu_usage_percentage: 18,
    max_concurrent_tasks: 50,
    last_active_at: new Date(),
    created_at: new Date('2024-01-01'),
    updated_at: new Date(),
  },
  {
    agent_id: 'agent-003',
    agent_type: 'legal_research',
    name: 'Legal Research Agent',
    name_urdu: 'قانونی تحقیق ایجنٹ',
    description: 'Performs intelligent legal research and analysis',
    description_urdu: 'ذہین قانونی تحقیق اور تجزیہ',
    version: '1.3.0',
    config: { searchDepth: 5, includeInternational: true },
    capabilities: ['law_search', 'precedent_analysis', 'argument_suggestions', 'citation'],
    dependencies: ['orchestrator', 'knowledge'],
    status: 'active',
    is_enabled: true,
    tasks_completed: 5678,
    tasks_in_progress: 34,
    tasks_failed: 8,
    average_response_time_ms: 850,
    accuracy_percentage: 94.2,
    uptime_percentage: 99.92,
    memory_usage_mb: 1024,
    cpu_usage_percentage: 35,
    max_concurrent_tasks: 30,
    last_active_at: new Date(),
    created_at: new Date('2024-01-01'),
    updated_at: new Date(),
  },
];

// =============================================================================
// MOCK PAYMENTS
// =============================================================================

export const MOCK_PAYMENTS: Payment[] = [
  {
    payment_id: 'payment-001',
    transaction_id: 'TXN-2026-001',
    case_id: 'case-001',
    payer_id: 'user-001',
    payee_id: 'lawyer-001',
    amount: 100000,
    currency: 'PKR',
    service_fee: 10000,
    lawyer_fee: 85000,
    tax_amount: 5000,
    discount_amount: 0,
    net_amount: 100000,
    payment_method: 'bank_transfer',
    payment_gateway: 'jazzcash',
    gateway_reference: 'JC-2026-XXXXX',
    status: 'completed',
    is_escrow: true,
    escrow_status: 'held',
    platform_commission: 10000,
    platform_commission_percentage: 10,
    created_at: new Date('2026-02-17'),
    processed_at: new Date('2026-02-17'),
    completed_at: new Date('2026-02-17'),
    updated_at: new Date('2026-02-17'),
  },
];

// =============================================================================
// DATABASE STATISTICS
// =============================================================================

export const MOCK_DB_STATS = {
  users: {
    total: 15420,
    active: 12350,
    clients: 14200,
    lawyers: 1100,
    admins: 120,
  },
  cases: {
    total: 8950,
    active: 3200,
    completed: 4800,
    pending: 950,
  },
  payments: {
    total: 12500,
    totalAmount: 485000000,
    currency: 'PKR',
    thisMonth: 1250,
    thisMonthAmount: 48500000,
  },
  lawyers: {
    total: 1100,
    verified: 980,
    active: 850,
    avgRating: 4.6,
  },
  documents: {
    total: 45600,
    verified: 42000,
    pending: 3600,
  },
};
