// =============================================================================
// EHB EXTENDED DATABASE - MOCK DATA
// Sample data for Phases 2, 3, 4
// =============================================================================

import {
  LawyerVerification, FranchiseOffice, LegalKnowledge, ComplianceRecord,
  Language, Country, LawyerHiringContract, ConsultationSession,
  SubscriptionPlan, LawyerPerformance, CaseWorkflow, CourtHearing,
  EvidenceRecord, LegalNotice, CaseTimelineExtended
} from './schemaExtended';

// =============================================================================
// PHASE 2 MOCK DATA
// =============================================================================

export const MOCK_LAWYER_VERIFICATIONS: LawyerVerification[] = [
  {
    verification_id: 'ver-001',
    lawyer_id: 'lawyer-001',
    license_number: 'ADV-LHC-2010-001',
    license_type: 'Advocate High Court',
    issuing_authority: 'Pakistan Bar Council',
    issuing_country: 'PK',
    issuing_state: 'Punjab',
    issue_date: new Date('2010-06-15'),
    bar_council_name: 'Pakistan Bar Council',
    bar_council_id: 'PBC-2010-12345',
    bar_registration_number: 'PBC-2010-12345',
    bar_registration_date: new Date('2010-06-15'),
    verification_status: 'verified',
    verification_method: 'document',
    verified_by: 'admin-001',
    verification_date: new Date('2025-01-15'),
    background_check_status: 'passed',
    background_check_date: new Date('2025-01-10'),
    renewal_required: true,
    renewal_reminder_sent: false,
    next_renewal_date: new Date('2027-06-15'),
    created_at: new Date('2024-06-01'),
    updated_at: new Date('2025-01-15'),
  },
];

export const MOCK_FRANCHISE_OFFICES: FranchiseOffice[] = [
  {
    franchise_id: 'franchise-001',
    franchise_code: 'EHB-PK-LHR-001',
    owner_id: 'user-franchise-001',
    owner_name: 'Ali Hassan',
    owner_contact_email: 'ali@ehblaw.com',
    owner_contact_phone: '+92300-1111111',
    country: 'PK',
    country_name: 'Pakistan',
    state_province: 'Punjab',
    city: 'Lahore',
    address: '123 Court Road, Lahore',
    postal_code: '54000',
    timezone: 'Asia/Karachi',
    franchise_name: 'EHB Law Services Lahore',
    franchise_name_local: 'EHB لاء سروسز لاہور',
    status: 'active',
    tier: 'premium',
    operational_since: new Date('2024-06-01'),
    operating_hours: {
      weekdays: { open: '09:00', close: '18:00' },
      saturday: { open: '10:00', close: '14:00' },
      sunday: { open: '', close: '', closed: true },
    },
    total_lawyers: 25,
    total_staff: 15,
    manager_name: 'Usman Khan',
    total_cases: 450,
    active_cases: 85,
    completed_cases: 365,
    success_rate: 84.5,
    average_rating: 4.7,
    total_revenue: 15000000,
    revenue_currency: 'PKR',
    platform_commission_rate: 10,
    commission_structure: 'tiered',
    services_offered: ['Family Law', 'Property Law', 'Civil Litigation', 'Criminal Defense'],
    specializations: ['divorce', 'property_dispute', 'civil_litigation', 'criminal_defense'],
    languages_supported: ['en', 'ur', 'pa'],
    agreement_signed: true,
    agreement_date: new Date('2024-05-15'),
    created_at: new Date('2024-05-15'),
    updated_at: new Date('2026-03-12'),
  },
  {
    franchise_id: 'franchise-002',
    franchise_code: 'EHB-PK-KHI-001',
    owner_id: 'user-franchise-002',
    owner_name: 'Fatima Siddiqui',
    owner_contact_email: 'fatima@ehblaw.com',
    owner_contact_phone: '+92321-2222222',
    country: 'PK',
    country_name: 'Pakistan',
    state_province: 'Sindh',
    city: 'Karachi',
    address: '456 Clifton, Karachi',
    postal_code: '75600',
    timezone: 'Asia/Karachi',
    franchise_name: 'EHB Law Services Karachi',
    status: 'active',
    tier: 'enterprise',
    operational_since: new Date('2024-08-01'),
    operating_hours: {
      weekdays: { open: '09:00', close: '19:00' },
      saturday: { open: '10:00', close: '15:00' },
      sunday: { open: '', close: '', closed: true },
    },
    total_lawyers: 35,
    total_staff: 20,
    total_cases: 620,
    active_cases: 120,
    completed_cases: 500,
    success_rate: 86.2,
    average_rating: 4.8,
    total_revenue: 25000000,
    revenue_currency: 'PKR',
    platform_commission_rate: 8,
    commission_structure: 'tiered',
    services_offered: ['Corporate Law', 'Family Law', 'Property Law', 'Banking Law'],
    specializations: ['corporate_law', 'divorce', 'property_dispute', 'banking_finance'],
    languages_supported: ['en', 'ur', 'sd'],
    agreement_signed: true,
    created_at: new Date('2024-07-15'),
    updated_at: new Date('2026-03-12'),
  },
  {
    franchise_id: 'franchise-003',
    franchise_code: 'EHB-AE-DXB-001',
    owner_id: 'user-franchise-003',
    owner_name: 'Ahmed Al-Rashid',
    owner_contact_email: 'ahmed@ehblaw.ae',
    owner_contact_phone: '+971501234567',
    country: 'AE',
    country_name: 'United Arab Emirates',
    city: 'Dubai',
    address: 'DIFC, Gate Building, Dubai',
    timezone: 'Asia/Dubai',
    franchise_name: 'EHB Law Services Dubai',
    status: 'active',
    tier: 'master',
    operational_since: new Date('2024-03-01'),
    operating_hours: {
      weekdays: { open: '08:00', close: '18:00' },
      saturday: { open: '09:00', close: '13:00' },
      sunday: { open: '', close: '', closed: true },
    },
    total_lawyers: 45,
    total_staff: 30,
    total_cases: 890,
    active_cases: 180,
    completed_cases: 710,
    success_rate: 89.5,
    average_rating: 4.9,
    total_revenue: 8500000,
    revenue_currency: 'AED',
    platform_commission_rate: 7,
    commission_structure: 'custom',
    services_offered: ['Corporate Law', 'International Law', 'Real Estate', 'Immigration'],
    specializations: ['corporate_law', 'immigration', 'property_dispute', 'contract_dispute'],
    languages_supported: ['en', 'ar', 'ur'],
    agreement_signed: true,
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2026-03-12'),
  },
];

export const MOCK_LANGUAGES: Language[] = [
  { language_id: 'lang-001', code: 'en', code_3: 'eng', name: 'English', native_name: 'English', direction: 'ltr', script: 'Latin', is_active: true, is_default: true, translation_coverage: 100, countries_primary: ['US', 'UK', 'AU', 'CA'], countries_secondary: ['PK', 'AE', 'IN'], total_users: 8500, ai_translation_available: true, ai_voice_available: true, ai_chat_available: true, display_order: 1, flag_emoji: '🇬🇧', created_at: new Date(), updated_at: new Date() },
  { language_id: 'lang-002', code: 'ur', code_3: 'urd', name: 'Urdu', native_name: 'اردو', direction: 'rtl', script: 'Arabic', is_active: true, is_default: false, translation_coverage: 95, countries_primary: ['PK'], countries_secondary: ['AE', 'UK'], total_users: 5200, ai_translation_available: true, ai_voice_available: true, ai_chat_available: true, display_order: 2, flag_emoji: '🇵🇰', created_at: new Date(), updated_at: new Date() },
  { language_id: 'lang-003', code: 'ar', code_3: 'ara', name: 'Arabic', native_name: 'العربية', direction: 'rtl', script: 'Arabic', is_active: true, is_default: false, translation_coverage: 85, countries_primary: ['AE', 'SA', 'EG'], countries_secondary: ['PK'], total_users: 2100, ai_translation_available: true, ai_voice_available: true, ai_chat_available: true, display_order: 3, flag_emoji: '🇦🇪', created_at: new Date(), updated_at: new Date() },
  { language_id: 'lang-004', code: 'hi', code_3: 'hin', name: 'Hindi', native_name: 'हिन्दी', direction: 'ltr', script: 'Devanagari', is_active: true, is_default: false, translation_coverage: 75, countries_primary: ['IN'], countries_secondary: ['AE', 'UK'], total_users: 1800, ai_translation_available: true, ai_voice_available: true, ai_chat_available: true, display_order: 4, flag_emoji: '🇮🇳', created_at: new Date(), updated_at: new Date() },
];

export const MOCK_COUNTRIES: Country[] = [
  {
    country_id: 'country-001', code: 'PK', code_3: 'PAK', name: 'Pakistan', official_name: 'Islamic Republic of Pakistan', native_name: 'پاکستان', region: 'Asia', subregion: 'Southern Asia', capital: 'Islamabad',
    legal_system: 'mixed', legal_system_description: 'Islamic law and English common law', highest_court: 'Supreme Court of Pakistan', court_hierarchy: ['Supreme Court', 'High Courts', 'District Courts', 'Session Courts', 'Magistrate Courts'],
    bar_council_name: 'Pakistan Bar Council', lawyer_licensing_authority: 'Pakistan Bar Council', currency_code: 'PKR', currency_name: 'Pakistani Rupee', currency_symbol: '₨',
    timezone: 'Asia/Karachi', timezones: ['Asia/Karachi'], phone_code: '+92', date_format: 'DD/MM/YYYY', official_languages: ['ur', 'en'], primary_language: 'ur',
    is_active: true, is_operational: true, launch_date: new Date('2024-01-01'), total_franchises: 5, total_lawyers: 450, total_cases: 3500,
    data_protection_law: 'Prevention of Electronic Crimes Act 2016', requires_local_data_storage: false, flag_emoji: '🇵🇰', created_at: new Date(), updated_at: new Date(),
  },
  {
    country_id: 'country-002', code: 'AE', code_3: 'ARE', name: 'United Arab Emirates', official_name: 'United Arab Emirates', native_name: 'الإمارات العربية المتحدة', region: 'Asia', subregion: 'Western Asia', capital: 'Abu Dhabi',
    legal_system: 'mixed', legal_system_description: 'Islamic law and civil law', highest_court: 'Federal Supreme Court', court_hierarchy: ['Federal Supreme Court', 'Courts of Appeal', 'Courts of First Instance', 'DIFC Courts'],
    bar_council_name: 'UAE Bar Association', currency_code: 'AED', currency_name: 'UAE Dirham', currency_symbol: 'د.إ',
    timezone: 'Asia/Dubai', timezones: ['Asia/Dubai'], phone_code: '+971', date_format: 'DD/MM/YYYY', official_languages: ['ar'], primary_language: 'ar',
    is_active: true, is_operational: true, launch_date: new Date('2024-03-01'), total_franchises: 3, total_lawyers: 180, total_cases: 1200,
    data_protection_law: 'Federal Decree-Law No. 45 of 2021', requires_local_data_storage: true, flag_emoji: '🇦🇪', created_at: new Date(), updated_at: new Date(),
  },
  {
    country_id: 'country-003', code: 'UK', code_3: 'GBR', name: 'United Kingdom', official_name: 'United Kingdom of Great Britain and Northern Ireland', region: 'Europe', subregion: 'Northern Europe', capital: 'London',
    legal_system: 'common_law', legal_system_description: 'English common law', highest_court: 'Supreme Court of the United Kingdom', court_hierarchy: ['Supreme Court', 'Court of Appeal', 'High Court', 'Crown Court', 'Magistrates Court'],
    bar_council_name: 'Bar Council of England and Wales', currency_code: 'GBP', currency_name: 'British Pound', currency_symbol: '£',
    timezone: 'Europe/London', timezones: ['Europe/London'], phone_code: '+44', date_format: 'DD/MM/YYYY', official_languages: ['en'], primary_language: 'en',
    is_active: true, is_operational: true, launch_date: new Date('2024-06-01'), total_franchises: 2, total_lawyers: 120, total_cases: 850,
    data_protection_law: 'UK GDPR', requires_local_data_storage: false, flag_emoji: '🇬🇧', created_at: new Date(), updated_at: new Date(),
  },
];

// =============================================================================
// PHASE 3 MOCK DATA
// =============================================================================

export const MOCK_HIRING_CONTRACTS: LawyerHiringContract[] = [
  {
    contract_id: 'contract-001',
    contract_number: 'EHB-CON-2026-00001',
    client_id: 'user-001',
    lawyer_id: 'lawyer-001',
    franchise_id: 'franchise-001',
    contract_type: 'monthly_retainer',
    contract_title: 'Monthly Legal Advisory',
    contract_description: 'Monthly legal advisory services for property matters',
    start_date: new Date('2026-01-01'),
    end_date: new Date('2026-12-31'),
    duration_months: 12,
    is_open_ended: false,
    auto_renew: true,
    scope_of_work: 'Property law advisory, document review, legal consultations',
    case_types_covered: ['property_dispute', 'land_ownership', 'property_transfer'],
    max_hours: 20,
    hours_used: 8,
    cases_used: 2,
    total_value: 1200000,
    currency: 'PKR',
    payment_terms: 'Monthly in advance',
    billing_frequency: 'monthly',
    monthly_fee: 100000,
    status: 'active',
    termination_notice_days: 30,
    client_signed: true,
    client_signed_at: new Date('2025-12-28'),
    lawyer_signed: true,
    lawyer_signed_at: new Date('2025-12-28'),
    created_at: new Date('2025-12-25'),
    updated_at: new Date('2026-03-01'),
  },
];

export const MOCK_CONSULTATION_SESSIONS: ConsultationSession[] = [
  {
    session_id: 'session-001',
    booking_number: 'EHB-BK-2026-00001',
    client_id: 'user-001',
    lawyer_id: 'lawyer-001',
    contract_id: 'contract-001',
    session_type: 'video_call',
    session_purpose: 'Property dispute consultation',
    scheduled_date: new Date('2026-03-15'),
    scheduled_time: '14:00',
    timezone: 'Asia/Karachi',
    duration_minutes: 60,
    buffer_minutes: 10,
    status: 'scheduled',
    meeting_link: 'https://meet.ehblaw.com/session-001',
    fee: 5000,
    currency: 'PKR',
    is_free: false,
    payment_status: 'paid',
    reminder_sent: true,
    is_recorded: false,
    recording_consent: true,
    requires_follow_up: false,
    booked_at: new Date('2026-03-10'),
    confirmed_at: new Date('2026-03-10'),
    created_at: new Date('2026-03-10'),
    updated_at: new Date('2026-03-12'),
  },
];

export const MOCK_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    plan_id: 'plan-001', plan_code: 'PLAN-BASIC-001', plan_name: 'Basic Legal Coverage', plan_name_local: 'بنیادی قانونی تحفظ',
    plan_description: 'Essential legal support for individuals', plan_description_local: 'افراد کے لیے ضروری قانونی معاونت',
    plan_type: 'basic', billing_cycle: 'monthly', base_price: 5000, currency: 'PKR', discount_annual: 15,
    features: [
      { feature_id: 'f1', feature_name: '2 Hours Consultation', is_highlighted: true, limit: 2, unit: 'hours' },
      { feature_id: 'f2', feature_name: 'Document Review', is_highlighted: false, limit: 3, unit: 'documents' },
      { feature_id: 'f3', feature_name: 'Email Support', is_highlighted: false },
    ],
    consultation_hours_included: 2, cases_included: 0, document_reviews_included: 3, legal_calls_included: 5,
    extra_hour_rate: 3000, extra_case_rate: 25000,
    support_level: 'email', response_time_hours: 24, priority_support: false, dedicated_lawyer: false,
    target_audience: 'individual', available_countries: ['PK', 'AE'],
    is_active: true, is_featured: false, display_order: 1,
    total_subscribers: 450, active_subscribers: 380,
    valid_from: new Date('2024-01-01'), created_at: new Date(), updated_at: new Date(),
  },
  {
    plan_id: 'plan-002', plan_code: 'PLAN-PREMIUM-001', plan_name: 'Premium Legal Protection', plan_name_local: 'پریمیم قانونی تحفظ',
    plan_description: 'Comprehensive legal coverage for businesses', plan_description_local: 'کاروبار کے لیے جامع قانونی تحفظ',
    plan_type: 'premium', billing_cycle: 'monthly', base_price: 25000, currency: 'PKR', discount_annual: 20,
    features: [
      { feature_id: 'f1', feature_name: '10 Hours Consultation', is_highlighted: true, limit: 10, unit: 'hours' },
      { feature_id: 'f2', feature_name: 'Unlimited Document Review', is_highlighted: true },
      { feature_id: 'f3', feature_name: '1 Case Included', is_highlighted: true, limit: 1, unit: 'case' },
      { feature_id: 'f4', feature_name: 'Priority Phone Support', is_highlighted: false },
      { feature_id: 'f5', feature_name: 'Contract Drafting', is_highlighted: false, limit: 2, unit: 'contracts' },
    ],
    consultation_hours_included: 10, cases_included: 1, document_reviews_included: 999, legal_calls_included: 20,
    extra_hour_rate: 2500, extra_case_rate: 20000,
    support_level: 'phone', response_time_hours: 4, priority_support: true, dedicated_lawyer: false,
    target_audience: 'small_business', available_countries: ['PK', 'AE', 'UK'],
    is_active: true, is_featured: true, display_order: 2,
    total_subscribers: 180, active_subscribers: 165,
    valid_from: new Date('2024-01-01'), created_at: new Date(), updated_at: new Date(),
  },
];

export const MOCK_LAWYER_PERFORMANCE: LawyerPerformance[] = [
  {
    performance_id: 'perf-001',
    lawyer_id: 'lawyer-001',
    period_type: 'monthly',
    period_start: new Date('2026-02-01'),
    period_end: new Date('2026-02-29'),
    cases_received: 15, cases_accepted: 12, cases_declined: 3, cases_completed: 8, cases_ongoing: 4, cases_won: 6, cases_lost: 1, cases_settled: 1,
    success_rate: 85.7, win_rate: 75, settlement_rate: 12.5,
    average_response_time_hours: 1.5, response_rate: 98, first_response_time_hours: 0.5,
    total_clients: 45, new_clients: 8, returning_clients: 37, client_retention_rate: 82,
    average_rating: 4.9, total_reviews: 35, five_star_reviews: 30, positive_review_rate: 97,
    total_earnings: 850000, currency: 'PKR', average_case_value: 106250, total_consultations: 22, consultation_earnings: 110000,
    profile_views: 450, contact_requests: 85, conversion_rate: 18.9,
    availability_hours: 160, hours_worked: 145, utilization_rate: 90.6,
    communication_score: 4.8, professionalism_score: 4.9, expertise_score: 4.9, value_score: 4.7, overall_score: 4.83,
    platform_rank: 5, category_rank: 2, city_rank: 1,
    badges_earned: ['Top Performer', 'Quick Responder', 'Client Favorite'],
    ai_performance_summary: 'Exceptional performance with high client satisfaction and success rate.',
    ai_strength_areas: ['Property Law', 'Client Communication', 'Case Preparation'],
    calculated_at: new Date('2026-03-01'),
    created_at: new Date('2026-03-01'),
    updated_at: new Date('2026-03-01'),
  },
];

// =============================================================================
// PHASE 4 MOCK DATA
// =============================================================================

export const MOCK_CASE_WORKFLOWS: CaseWorkflow[] = [
  {
    workflow_id: 'workflow-001',
    case_id: 'case-001',
    current_stage: 'hearing_scheduled',
    current_stage_name: 'Hearing Scheduled',
    current_status: 'in_progress',
    progress_percentage: 65,
    stages_completed: 8,
    total_stages: 12,
    stages: [
      { stage: 'case_created', stage_name: 'Case Created', stage_order: 1, status: 'completed', started_at: new Date('2026-02-15'), completed_at: new Date('2026-02-15'), duration_days: 0, is_mandatory: true, dependencies: [] },
      { stage: 'information_collected', stage_name: 'Information Collected', stage_order: 2, status: 'completed', started_at: new Date('2026-02-15'), completed_at: new Date('2026-02-16'), duration_days: 1, is_mandatory: true, dependencies: ['case_created'] },
      { stage: 'documents_uploaded', stage_name: 'Documents Uploaded', stage_order: 3, status: 'completed', started_at: new Date('2026-02-16'), completed_at: new Date('2026-02-18'), duration_days: 2, is_mandatory: true, dependencies: ['information_collected'] },
      { stage: 'lawyer_assigned', stage_name: 'Lawyer Assigned', stage_order: 4, status: 'completed', started_at: new Date('2026-02-18'), completed_at: new Date('2026-02-19'), duration_days: 1, is_mandatory: true, dependencies: ['documents_uploaded'] },
      { stage: 'case_reviewed', stage_name: 'Case Reviewed', stage_order: 5, status: 'completed', started_at: new Date('2026-02-19'), completed_at: new Date('2026-02-22'), duration_days: 3, is_mandatory: true, dependencies: ['lawyer_assigned'] },
      { stage: 'legal_notice_sent', stage_name: 'Legal Notice Sent', stage_order: 6, status: 'completed', started_at: new Date('2026-02-25'), completed_at: new Date('2026-03-01'), duration_days: 4, is_mandatory: false, dependencies: ['case_reviewed'] },
      { stage: 'court_filed', stage_name: 'Court Filed', stage_order: 7, status: 'completed', started_at: new Date('2026-03-05'), completed_at: new Date('2026-03-08'), duration_days: 3, is_mandatory: true, dependencies: ['case_reviewed'] },
      { stage: 'hearing_scheduled', stage_name: 'Hearing Scheduled', stage_order: 8, status: 'in_progress', started_at: new Date('2026-03-10'), is_mandatory: true, dependencies: ['court_filed'] },
    ],
    started_at: new Date('2026-02-15'),
    expected_completion_date: new Date('2026-08-15'),
    time_in_current_stage_days: 2,
    is_blocked: false,
    auto_progress_enabled: true,
    ai_recommended_next_step: 'Prepare evidence documents for first hearing',
    ai_estimated_days_remaining: 155,
    created_at: new Date('2026-02-15'),
    updated_at: new Date('2026-03-12'),
  },
];

export const MOCK_COURT_HEARINGS: CourtHearing[] = [
  {
    hearing_id: 'hearing-001',
    case_id: 'case-001',
    hearing_number: 1,
    hearing_type: 'preliminary',
    hearing_purpose: 'First hearing - case introduction',
    hearing_purpose_local: 'پہلی سماعت - کیس کا تعارف',
    court_name: 'Civil Court Lahore',
    court_branch: 'Branch II',
    court_room: 'Room 15',
    court_address: 'Civil Court Complex, Mall Road, Lahore',
    judge_name: 'Justice Ahmed Raza',
    scheduled_date: new Date('2026-03-25'),
    scheduled_time: '10:30',
    timezone: 'Asia/Karachi',
    expected_duration_minutes: 45,
    status: 'scheduled',
    postponement_count: 0,
    client_present: true,
    lawyer_present: true,
    agenda: ['Case introduction', 'Document verification', 'Next date scheduling'],
    next_steps: ['Prepare property documents', 'Gather witness statements'],
    reminder_sent: true,
    reminder_date: new Date('2026-03-22'),
    created_at: new Date('2026-03-10'),
    updated_at: new Date('2026-03-12'),
  },
];

export const MOCK_LEGAL_NOTICES: LegalNotice[] = [
  {
    notice_id: 'notice-001',
    case_id: 'case-001',
    notice_number: 'LN-2026-00001',
    notice_type: 'legal_notice',
    notice_title: 'Legal Notice for Property Possession',
    notice_title_local: 'جائیداد کے قبضے کا قانونی نوٹس',
    sender_id: 'user-001',
    sender_name: 'Ahmad Khan',
    sender_address: '123 Gulberg III, Lahore',
    sender_lawyer_id: 'lawyer-001',
    recipient_name: 'Muhammad Ali',
    recipient_address: '456 Model Town, Lahore',
    subject: 'Demand for vacation of illegally occupied property',
    body_text: 'This legal notice is being served upon you demanding immediate vacation of the property...',
    legal_sections_cited: ['Transfer of Property Act Section 54', 'Specific Relief Act Section 6'],
    relief_sought: 'Vacation of property within 15 days',
    response_deadline_days: 15,
    response_deadline_date: new Date('2026-03-16'),
    requires_response: true,
    status: 'delivered',
    status_history: [
      { status: 'drafted', changed_at: new Date('2026-02-25'), changed_by: 'lawyer-001' },
      { status: 'approved', changed_at: new Date('2026-02-26'), changed_by: 'user-001' },
      { status: 'sent', changed_at: new Date('2026-03-01') },
      { status: 'delivered', changed_at: new Date('2026-03-03') },
    ],
    drafted_by: 'lawyer-001',
    drafted_at: new Date('2026-02-25'),
    approved_by: 'user-001',
    approved_at: new Date('2026-02-26'),
    delivery_method: 'registered_post',
    sent_at: new Date('2026-03-01'),
    delivery_reference: 'RP-2026-123456',
    delivered_at: new Date('2026-03-03'),
    response_received: false,
    ai_generated: true,
    ai_template_used: 'property_possession_notice',
    ai_confidence_score: 94.5,
    created_at: new Date('2026-02-25'),
    updated_at: new Date('2026-03-03'),
  },
];

// =============================================================================
// EXTENDED DATABASE STATISTICS
// =============================================================================

export const EXTENDED_MOCK_STATS = {
  phase2: {
    verifications: { total: 980, verified: 920, pending: 45, rejected: 15 },
    franchises: { total: 12, active: 10, countries: 5, revenue: 125000000 },
    knowledge: { articles: 5600, laws: 2300, precedents: 1850, guides: 450 },
    countries: { operational: 8, planned: 15 },
    languages: { active: 6, planned: 10 },
  },
  phase3: {
    contracts: { total: 2500, active: 1850, completed: 580, terminated: 70 },
    sessions: { total: 8900, completed: 7800, scheduled: 850, cancelled: 250 },
    subscriptions: { total: 630, active: 545, revenue: 32000000 },
    avgPerformanceScore: 4.5,
  },
  phase4: {
    workflows: { total: 8950, active: 3200 },
    hearings: { scheduled: 450, completed: 3200, postponed: 380 },
    evidence: { total: 25600, verified: 23000 },
    notices: { total: 4500, delivered: 4200, responded: 3100 },
  },
};
